{% set version = "1.2.1" %}

package:
  name: setuptools_scm_git_archive
  version: {{ version }}

source:
  fn: setuptools_scm_git_archive-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/s/setuptools_scm_git_archive/setuptools_scm_git_archive-{{ version }}.tar.gz
  sha256: 2d964ebba5f91488e4a2a00da6b8106858325c6684d0099c482558a2d9705915

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools_scm

test:
  requires:
    - setuptools
  imports:
    - setuptools_scm_git_archive

about:
  home: https://github.com/Changaco/setuptools_scm_git_archive/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: setuptools_scm plugin for git archives

extra:
  recipe-maintainers:
    - wesm
    - xhochy
