{% set name = "setuptools_scm_git_archive" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setuptools_scm_git_archive-{{ version }}.tar.gz
  sha256: 92e8149c1f4a62fe170962b4ff8cb3d53bfa90fc944f1f1758cebaef56a67f13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools_scm

test:
  requires:
    - setuptools
  imports:
    - setuptools_scm_git_archive

about:
  home: https://github.com/Changaco/setuptools_scm_git_archive/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: setuptools_scm plugin for git archives

extra:
  recipe-maintainers:
    - thewchan
    - wesm
    - xhochy
