{% set version = "1.1" %}

package:
  name: setuptools_scm_git_archive
  version: {{ version }}

source:
  fn: setuptools_scm_git_archive-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/s/setuptools_scm_git_archive/setuptools_scm_git_archive-{{ version }}.tar.gz
  sha256: 6026f61089b73fa1b5ee737e95314f41cb512609b393530385ed281d0b46c062

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools_scm

test:
  requires:
    - setuptools
  imports:
    - setuptools_scm_git_archive

about:
  home: https://github.com/Changaco/setuptools_scm_git_archive/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'setuptools_scm plugin for git archives'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
